/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.30
 * Generated at: 2014-05-19 14:09:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.*;
import did.*;

public final class info_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

//Recupero i dati ottenuti dalle interrogazioni e passati attraverso l'oggetto request

String dir = (String)request.getAttribute("info");

      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<title>DIPARTIMENTO DI INFORMATICA</title>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../page.css\" />\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<h1>Informazioni Generali</h1>\n");
      out.write("<b>Sede :</b><br/>\n");
      out.write("    Strada le Grazie 15 - 37134 Verona<br/>\n");
      out.write("<b>Direttore :</b><br/>\n");
      out.write("    Prof. ");
      out.print( dir );
      out.write(" <br/>\n");
      out.write("<b>Direttore Vicario :</b><br/>\n");
      out.write("    Prof. Leonard Peter  Bos<br/>\n");
      out.write("<b>Contatto :</b><br/>\n");
      out.write("    Segreteria amministrativa DI Informatica<br/>\n");
      out.write("<b>Edificio :</b><br/>\n");
      out.write("    Ca' Vignal 2<br/>\n");
      out.write("<b>Orario di apertura al pubblico :</b><br/>\n");
      out.write("    9.00 - 12.00<br/>\n");
      out.write("<b>Telefono :</b><br/>\n");
      out.write("    045 802 7071 - 045 8027802<br/>\n");
      out.write("<b>Fax :</b><br/>\n");
      out.write("    045 802 7068<br/>\n");
      out.write("<b>E-mail :</b><br/>\n");
      out.write("    segreteria.di@ateneo.univr.it<br/>\n");
      out.write("<br/>\n");
      out.write("<b><h4>Descrizione del dipartimento</h4></b><br/>\n");
      out.write("<br/>\n");
      out.write(" Il Dipartimento di Informatica promuove numerose attività didattiche e di ricerca basate su un continuo di competenze che vanno dalla matematica alla fisica attraverso l'informatica vista come scienze e ingegneria.\n");
      out.write("Le aree di ricerca attive sono: la matematica discreta e applicata, l'informatica teorica, i sistemi intelligenti, i sistemi informativi, l'ingegneria del software e la sicurezza, l'informatica applicata,\n");
      out.write("i sistemi ciberfisici e la fisica applicata e della materia.\n");
      out.write("A partire da queste competenze, il Dipartimento di Informatica ha rivolto da sempre particolare attenzione sia alla produzione scientifica (2000 pubblicazioni internazionali nell'ultimo settennio), alla\n");
      out.write("partecipazione a progetti finanziati da enti internazionali e nazionali (26 progetti per 7.7 milioni di euro) come all'attività di collaborazione con le imprese mediante ricerca applicata a forte ricaduta tecnologica\n");
      out.write("(5 spin-off, 10 brevetti, 253 progetti per 4.8 milioni di euro).<br/><br/> \n");
      out.write("\n");
      out.write("<br/><b><h4>Collegio Didattico di Informatica</h4></b><br/>\n");
      out.write("    Al Collegio Didattico di Informatica competono la definizione e la modifica di regolamenti, ordinamenti e piani didattici dei Corsi di Studio (CdS) afferenti alle classi di laurea L31 (Informatica e Bioinformatica) e LM18-32 (Ingegneria e scienze informatiche), la definizione dei carichi didattici, la proposta di affidamento dei vari insegnamenti ed utilizzo degli assistenti didattici, l’assicurazione della qualità dei CdS ai sensi di legge, l’amministrazione degli appelli d’esame e di laurea con l’identificazione delle relative commissioni, la gestione delle pratiche studenti. \n");
      out.write("<br/><b><h4>Collegio Didattico di Matematica</h4></b><br/>\n");
      out.write("    Al Collegio Didattico di Matematica competono la definizione e la modifica di regolamenti, ordinamenti e piani didattici dei Corsi di Studio (CdS) afferenti alle classi di laurea L35 (Matematica Applicata) e LM40 (Matematica), la definizione dei carichi didattici, la proposta di affidamento dei vari insegnamenti ed utilizzo degli assistenti didattici, l’assicurazione della qualità dei CdS ai sensi di legge, l’amministrazione degli appelli d’esame e di laurea con l’identificazione delle relative commissioni, la gestione delle pratiche studenti. \n");
      out.write("<br/><b><h4>Comitato Scientifico del Master Universitario in Computer game development (I livello)</h4></b><br/>\n");
      out.write("    Al comitato scientifico del master universitario in Computer game development competono la definizione delle linee guida del master, la stesura del piano didattico, la selezione delle aziende partner, l'identificazione delle prove intermedie e l'approvazione dell'esame finale. Inoltre è di competenza del comitato scientifico master la discussione e la presa in carico di casi particolari. \n");
      out.write("<br/><b><h4>Consiglio del Dipartimento di Informatica</h4></b><br/>\n");
      out.write("    Le competenze del Consiglio di Dipartimento sono indicate nell'art. 35 dello Statuto dell'Università.\n");
      out.write("    In particolare il Consiglio approva il bilancio di previsione del Dipartimento, le eventuali note di variazione in corso d'anno, nonché il conto consuntivo\n");
      out.write("    Il Consiglio, inoltre, programma le attività del Dipartimento e svolge tutti gli altri compiti che gli sono attribuiti dalle leggi, dallo Statuto e dai Regolamenti dell'Ateneo.\n");
      out.write("    Il Consiglio, infine, può delegare alla Giunta l'esercizio di specifiche competenze.\n");
      out.write("    Le modalità di funzionamento del Consiglio sono contenute nel Regolamento del Dipartimento.\n");
      out.write("<br/><br/><br/><br/>\n");
      out.write("<a href=?ps> Home </a>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
