/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.30
 * Generated at: 2014-05-22 14:10:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.*;
import did.*;

public final class insegnamenti_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

 String nome = ""; 
 String nomePrec = ""; 
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--\tCorsi.jsp: \n");
      out.write("\tLa JSP visualizza la lista di tutti i corsi di studio attivi e gestiti da un\n");
      out.write("\tdiparitmento passato come parametro idDip.\n");
      out.write("-->\n");
      out.write("\n");
      out.write("<!-- Eseguo gli import necessari -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write('\n');
      out.write("\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("\n");
 
            Vector iddid = (Vector) request.getAttribute("insegn");
            
            InsErogatoBean iddidb;

      out.write("\n");
      out.write("\n");
      out.write("<title>Corsi di Studio Esistenti</title>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../page.css\" />\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    <h2>INSEGNAMENTI: </h2><br>\n");
      out.write("\n");
      out.write("<hr align=\"left\" size=\"5\" width=\"100%\" color=\"blue\" noshade>\n");
      out.write("\n");
 for (int i = 0; i < iddid.size(); i++)
{
        iddidb = (InsErogatoBean) iddid.get(i); 
        nome = iddidb.getNomeFromInsegn();

      out.write("\n");
      out.write("\n");
      out.write("<ul>\n");
      out.write("\n");
 if (!nome.equals(nomePrec))
    {

      out.write("\n");
      out.write("<hr align=\"left\" size=\"1\" width=\"100%\" color=\"yellow\" noshade>\n");
      out.write("\n");
      out.write("    <li> <b> Codice: </b> ");
      out.print( iddidb.getCodiceFromInsegn() );
      out.write(' ');
      out.print(iddidb.getModulo());
      out.write(" </li>\n");
      out.write("\n");
      out.write("    <li> <b> Nome:</b> ");
      out.print( iddidb.getNomeFromInsegn() );
      out.write(" </li>\n");
      out.write("\n");
      out.write("    <li> <b> Crediti:</b> ");
      out.print( iddidb.getCreditiFromInsErogato() );
      out.write(" </li>\n");
      out.write("\n");
      out.write("\n");
 
     }

    if ( iddidb.getNomeModuloFromInsErogato() != null )
    { 

    
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        <li> <b> Nome Modulo:</b> ");
      out.print( iddidb.getNomeModuloFromInsErogato() );
      out.write("  </li>    \n");
      out.write("\n");
      out.write("        <li> <b> CreditiModulo:</b> ");
      out.print( iddidb.getCreditiModFromInsErogato() );
      out.write(" </li>\n");
      out.write("\n");
   }


      out.write("\n");
      out.write("    </ul>\n");
      out.write("\n");
  nomePrec = nome;  } 
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<a href=?ps> Home </a>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
